### PR TITLE
Enable wayland support

### PR DESCRIPTION
**Pull request by kenvandine**
Adds args necessary to enable wayland in electron

### CODE REVIEW

**Review by lucyllewy — DISMISSED** [review]
LGTM - Just need to wait on the build check before we merge.

**Comment by lucyllewy** [comment]
This causes a regression: #74

**Comment by jnsgruk** [comment]
@kenvandine @lucyllewy it might be worth picking this one back up once the release workflow completes today - the latest version of Mattermost bumps the electron version :)

**Comment by kenvandine** [comment]
I've rebased my branch and tested again with 5.6 and the resize bug still persist.  Looking at the various upstream references, wayland with hidpi issues are resolved but not the resizing bug.

**Comment by jnsgruk** [comment]
Closing this for now. Commits have got a bit messy through the rebase, and we're still working against upstream issues. Let's follow the upstream and revisit this another time.

**Pull request closed without merging**
