### PR TITLE
docs: update snapcraft.yaml to include more detailed metadata

### PR DESCRIPTION
**Pull request by jnsgruk**
Replacement for #87 - the branch randomly became protected, so I was unable to push more commits :man_shrugging:

### CODE REVIEW

**Comment by jnsgruk** [comment]
@merlijn-sebrechts might be worth adjusting the protected branch settings so they only apply to `candidate` :)

In fact - I need to push a change here and can't - I'll wait on the branch not being protected.

**Comment by merlijn-sebrechts** [comment]
Oh, wow, you should not be allowed to create new branches on this repo :scream:

**Comment by jnsgruk** [comment]
Hah, okay well feel free to close this, and I'll open from a fork - would you prefer that?

**Comment by merlijn-sebrechts** [comment]
Yes, create a fork please.

I modified the permissions, so it should now suggest to create a fork when you edit using the web ui and disallow you from creating a new branch. Can you check this?

**Comment by merlijn-sebrechts** [comment]
Snapcrafters had "maintainer" permissions instead of "write" permissions. As a result, they could bypass some branch protection features and access some settings of the repos.


To give some context, because this might seem draconian: 

Creating new branches is a common way to [steal repository secrets and gain unauthorized access](https://medium.com/cider-sec/bypassing-required-reviews-using-github-actions-6e1b29135cc7) to a repository. I locked this down specifically to prevent such attacks. We also use an Environment locked to the `candidate` branch as a second layer of defense against stealing these secrets.

Permissions and security for GitHub actions and Secrets is quite difficult to get right, and it's made worse by

* having a bot that is permitted to push directly to the repo without any checks.
* having a large collection of semi-trusted people with write access to all repos

As we just saw, these permissions are hard to get right, and we were "saved" right now by the fact we had two layers of defense (Disallow creating new branches + Using Environments for secrets). As a result, I think we need to keep it like this. This protects us against both configuration errors (like this one) and actual GitHub vulnerabilities. People have been able to find many vulnerabilities in GitHub actions, and I want to avoid such a vulnerability giving people access to our large userbase.

**Pull request closed without merging**
