### PR TITLE
Add the 'process-control' interface.

### PR DESCRIPTION
**Pull request by jnsgruk**
This PR is mostly here for discussion. It adds the `process-control` interface to the snap, and some instructions to connect it. 

It solves a problem on my machine at least, where my kernel log gets flooded with messages like the following:

```
[ 4753.457736] audit: type=1326 audit(1631654267.163:3125): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.mattermost-desktop.mattermost-desktop pid=157459 comm="mattermost-desk" exe="/snap/mattermost-desktop/379/opt/Mattermost/mattermost-desktop" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3e636d7c7f code=0x50000
[ 4753.457822] audit: type=1326 audit(1631654267.163:3126): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.mattermost-desktop.mattermost-desktop pid=157459 comm="mattermost-desk" exe="/snap/mattermost-desktop/379/opt/Mattermost/mattermost-desktop" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3e636d7c7f code=0x50000
[ 4754.099602] audit: type=1326 audit(1631654267.807:3127): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.mattermost-desktop.mattermost-desktop pid=157459 comm="mattermost-desk" exe="/snap/mattermost-desktop/379/opt/Mattermost/mattermost-desktop" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3e636d7c7f code=0x50000
[ 4754.099789] audit: type=1326 audit(1631654267.807:3128): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.mattermost-desktop.mattermost-desktop pid=157459 comm="mattermo:gdrv0" exe="/snap/mattermost-desktop/379/opt/Mattermost/mattermost-desktop" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7f3e636d7c7f code=0x50000
```

Doing some digging, syscall 203 is in fact sched_setaffinity. I ran `strace` to confirm:

```
❯ sudo strace -p 157459 -e sched_setaffinity
strace: Process 157459 attached
sched_setaffinity(157516, 128, [12, 13, 14, 15, 16, 17]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157478, 128, [12, 13, 14, 15, 16, 17]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [12, 13, 14, 15, 16, 17]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [6, 7, 8, 9, 10, 11]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [6, 7, 8, 9, 10, 11]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [18, 19, 20, 21, 22, 23]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [18, 19, 20, 21, 22, 23]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [18, 19, 20, 21, 22, 23]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [18, 19, 20, 21, 22, 23]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [6, 7, 8, 9, 10, 11]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [12, 13, 14, 15, 16, 17]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [0, 1, 2, 3, 4, 5]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [12, 13, 14, 15, 16, 17]) = -1 EPERM (Operation not permitted)
sched_setaffinity(157516, 128, [12, 13, 14, 15, 16, 17]) = -1 EPERM (Operation not permitted)
```

### CODE REVIEW

**Comment by diddledani** [comment]
While I don't mind adding the `process-control` plug, I will steadfastly advocate against instructing users to connect it on install because of the same reasons that the review team on forum.snapcraft.io will refuse to grant an automatic connection via the store assertions mechanism.

**Comment by jnsgruk** [comment]
I've updated the PR to remove the instruction for now, though I do wonder if there should be some documentation somewhere (like an FAQ, maybe?) that indicates it is an option should the issue arise -- that is assuming we can't find the underlying issue, though I suspect that is somewhere deeper in the Electron or Mattermost code.

**Comment by anonymouse64** [comment]
I mentioned this offline, but I too am -1 for mattermost-desktop using the process-control interface, here's what I said repeated publicly for clarity:

giving a chat app access to read all the memory access of all other apps doesn't seem reasonable. I think the "best" solution is for AppArmor/Seccomp to be able to allow a snap to do sched_setaffinity on only a snap's own processes, however such fine grained policy is not yet representable in the LSM backends to my knowledge and the next best thing after that would be to add a silence/deny rule for this system call, but unfortunately snapd's seccomp bpf compiler doesn't currently have such a feature, so we are left with just granting the full, unfiltered sched_setaffinity to certain electron apps. We already did this for the `allow-sandbox: true` variant of the browser-support interface, but the `allow-sandbox: true` variant is really only meant for proper browsers that need to fully implement a sandbox like chromium or firefox for example. So really IMHO the best thing if this problem is indeed widespread is to add `sched_setaffinity` to the base version of browser-support (i.e. without the `allow-sandbox: true` rule)

**Comment by jnsgruk** [comment]
Thanks for the detailed response. I'll dig into this on my machine, as it seems others are not experiencing this and I can see why adding this interface could be seen as a bit intrusive. 

FWIW, I don't see the issue with the built snap resulting from #43, which bumps the version of Mattermost to 4.7.2, and rebases the snap onto `core20`.

**Pull request closed without merging**
